### ISSUE TITLE
Exceptions when converting between MGRS and LatLong near the equator.

### ISSUE THREAD

**Issue by James-Fryer** [GEOINT/jeotrans#3]
Using the following CoordinateTestCase
```
         /*
         * south-western hemisphere (Isla Santiago, Galápagos Islands)
         *
         * Geodetic -0.338917, -90.669525
         * UTM 759391.02 9962508.26
         * MGRS 15MYV5939162508
         * TM LONGITUDE OUT OF RANGE
         * PS LATITUDE OUT OF RANGE
         */
        CoordinateTestCase is = new CoordinateTestCase(LatLong.valueOf(-0.338917, -90.669525, NonSI.DEGREE_ANGLE));
        is.setExpectedMGRS(MGRS.valueOf(15, 'M', "YV".toCharArray(), 59391, 62508, SI.METER));
        is.setExpectedUTM(UTM.valueOf(15, 'M', 759391.02, 9962508.26, SI.METER));
        defaultTestCases.add(is);
```

and running the MGRSTest class, the following exceptions are raised:

```
MGRS.latLongToMgrs
Testing [-0.338917 °, -90.66952499999999 °](expected: 15M YV 59391 62508)   
javax.measure.converter.ConversionException: Northing outside of valid range (depending on ellipsoid and projection parameters)

	at org.jscience.geography.coordinates.crs.TransverseMercatorCRS.positionOf(TransverseMercatorCRS.java:514)
	at org.jscience.geography.coordinates.crs.TransverseMercatorCRS.positionOf(TransverseMercatorCRS.java:37)
	at org.jscience.geography.coordinates.crs.CoordinateReferenceSystem$GeneralConverter.convert(CoordinateReferenceSystem.java:92)
	at org.geoint.jeotrans.coordinate.TransverseMercator.transverseMercatorToLatLong(TransverseMercator.java:268)
	at org.jscience.geography.coordinates.crs.UtmCRS.positionOf(UtmCRS.java:258)
	at org.jscience.geography.coordinates.crs.UtmCRS.positionOf(UtmCRS.java:40)
	at org.jscience.geography.coordinates.crs.CoordinateReferenceSystem$GeneralConverter.convert(CoordinateReferenceSystem.java:92)
	at org.geoint.jeotrans.coordinate.UTM.utmToLatLong(UTM.java:374)
	at org.jscience.geography.coordinates.crs.MgrsCRS.utmToMgrs(MgrsCRS.java:282)
	at org.jscience.geography.coordinates.crs.MgrsCRS.coordinatesOf(MgrsCRS.java:130)
	at org.jscience.geography.coordinates.crs.MgrsCRS.coordinatesOf(MgrsCRS.java:42)
	at org.jscience.geography.coordinates.crs.CoordinateReferenceSystem$GeneralConverter.convert(CoordinateReferenceSystem.java:94)
	at org.geoint.jeotrans.coordinate.MGRS.latLongToMgrs(MGRS.java:301)
	at org.geoint.jeotrans.coordinate.MGRSTest.testLatLongToMgrs(MGRSTest.java:94)
```

```
MGRS.mgrsToLatLong
Testing 15M YV 59391 62508(expected: [-0.338917 °, -90.66952499999999 °])   
javax.measure.converter.ConversionException: Northing outside of valid range (depending on ellipsoid and projection parameters)

	at org.jscience.geography.coordinates.crs.TransverseMercatorCRS.positionOf(TransverseMercatorCRS.java:514)
	at org.jscience.geography.coordinates.crs.TransverseMercatorCRS.positionOf(TransverseMercatorCRS.java:37)
	at org.jscience.geography.coordinates.crs.CoordinateReferenceSystem$GeneralConverter.convert(CoordinateReferenceSystem.java:92)
	at org.geoint.jeotrans.coordinate.TransverseMercator.transverseMercatorToLatLong(TransverseMercator.java:268)
	at org.jscience.geography.coordinates.crs.UtmCRS.positionOf(UtmCRS.java:258)
	at org.jscience.geography.coordinates.crs.UtmCRS.positionOf(UtmCRS.java:40)
	at org.jscience.geography.coordinates.crs.CoordinateReferenceSystem$GeneralConverter.convert(CoordinateReferenceSystem.java:92)
	at org.geoint.jeotrans.coordinate.UTM.utmToLatLong(UTM.java:374)
	at org.jscience.geography.coordinates.crs.MgrsCRS.utmToMgrs(MgrsCRS.java:282)
	at org.jscience.geography.coordinates.crs.MgrsCRS.coordinatesOf(MgrsCRS.java:130)
	at org.jscience.geography.coordinates.crs.MgrsCRS.coordinatesOf(MgrsCRS.java:42)
	at org.jscience.geography.coordinates.crs.CoordinateReferenceSystem$GeneralConverter.convert(CoordinateReferenceSystem.java:94)
	at org.geoint.jeotrans.coordinate.MGRS.latLongToMgrs(MGRS.java:301)
	at org.geoint.jeotrans.coordinate.MGRSTest.testMgrsToLatLong(MGRSTest.java:124)
```
	
Interestingly enough the same error is occurring when going from LatLong to MGRS and when going from MGRS to LatLong.

The same exception can be seen for any Latitude value between (but not including) 0.0 and -1.0.

**Comment by smsiebe** [comment]
Ooh, this is a fun one.  Thanks for submitting, I'll work on it today.

**Comment by James-Fryer** [comment]
Is there anything further I can assist with on this one?  I'm happy to run test cases and test code through our stuff if it would help.

**Comment by smsiebe** [comment]
Sorry for the delay...job had to take priority.  I'm looking at the latest NGA geotrans code and there has certainly been some updates since I ported the code.  I'm going to verify geotrans translates the code properly and, if so, will either re-port the code or create a JNI adapter to the latest geotrans source.  Good weekend project. =)

**Comment by James-Fryer** [comment]
Definitely no concerns about the delay, there is no issue there. Your code, your time :)

If you need more testing etc we are happy to help out here.
